version: '3.8'

services:
  uruguay-in-wines:
    container_name: uruguay-in-wines
    image: raphauy/uruguay-in-wines:latest
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8058:3000
    networks:
      - rc-network

networks:
  rc-network:
    external:
      name: rc-network
